// Activate experimental attribute for Keyboard Shortcut keys
:experimental:

= Lab 2-1: OpenShift Data Foundationをデプロイするためのnodeを準備する

== Labの概要
このLabでは Red Hat OpenShift Data Foundation(ODF) 4をデプロイするための新しいnodeを準備します。 +
ODFは、通常ユーザーアプリケーションが稼働するworker nodeで共存して稼働することも可能ですが、本LabではODF専用のworker nodeを作成します。

IPI(Installer Provisioned Infrastructure)方式でインストールしたOpenShift Container Platform(OCP)クラスターでは、**Machine Set**を使用することで、簡単に新しいnodeを追加することが可能です。 +
本Labでも**Machine Set**を使って新しいnodeを追加します。

=== このLabで学習する内容

* OCPクラスターに新規の**Machine Set**を追加し、ODF用のworker nodeを追加する
* 追加したworker nodeに、ODFで使用するためのラベルを付ける


[[labexercises]]

== 2-1-0. Bastionサーバーからログアウトする

**もしBastionサーバーにログインしている場合は、ログアウトして下さい。** +
Bastionサーバー上では以下の作業ができないものがあります。

== 2-1-1. OCPクラスターでMachine Setを作成してworker nodeを追加する

このセクションでは、ODF用に3つの *Machine Set* を追加します。 +
はじめにOCPクラスターに3つのworker nodeがあることを確認します。

[source,role="execute"]
----
oc get nodes -l node-role.kubernetes.io/worker -l '!node-role.kubernetes.io/master'
----

.出力例:

----
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-128-156.us-east-2.compute.internal   Ready    worker   21h   v1.22.3+b93fd35
ip-10-0-181-21.us-east-2.compute.internal    Ready    worker   21h   v1.22.3+b93fd35
ip-10-0-214-18.us-east-2.compute.internal    Ready    worker   21h   v1.22.3+b93fd35
----

ここで *Machine Set* を使用して、さらに3つのworker nodeをクラスターに追加します。 +
まず既存の *Machine Set* を確認します。AWS Availability Zone(us-east-2a、us-east-2b、us-east-2c)ごとに *Machine Set* があることがわかります。

[source,role="execute"]
----
oc get machinesets -n openshift-machine-api
----

.出力例:

----
NAME                                    DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-58kkd-nmncw-worker-us-east-2a   1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2b   1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2c   1         1         1       1           21h
----

それでは、次を実行してODFで使用する新しい *Machine Set* を作成します。

[source,role="execute"]
----
bash {{ HOME_PATH }}/support/machineset-generator.sh 3 workerocs 0 | oc create -f -
----

それぞれのAvailability Zoneごとに、新しい *Machine Set* ができたことが確認できるはずです。

[source,role="execute"]
----
oc get machinesets -n openshift-machine-api
----

.出力例:

----
NAME                                       DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-58kkd-nmncw-worker-us-east-2a      1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2b      1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2c      1         1         1       1           21h
cluster-58kkd-nmncw-workerocs-us-east-2a   0         0                             36s
cluster-58kkd-nmncw-workerocs-us-east-2b   0         0                             36s
cluster-58kkd-nmncw-workerocs-us-east-2c   0         0                             36s
----

この時点では `DESIRED` と `CURRENT` が 0、つまり *Machine* がないため、nodeは作成されません。 +
nodeを作成するためには、*Machine Set* をスケールして、*Machine* を作成します。 +
このLabでは、各Availability Zoneに1 nodeずつ、合計3 nodeを作成します。

[source,role="execute"]
----
oc get machinesets -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=workerocs -o name | xargs oc scale -n openshift-machine-api --replicas=1
----

.出力例:

----
machineset.machine.openshift.io/cluster-58kkd-nmncw-workerocs-us-east-2a scaled
machineset.machine.openshift.io/cluster-58kkd-nmncw-workerocs-us-east-2b scaled
machineset.machine.openshift.io/cluster-58kkd-nmncw-workerocs-us-east-2c scaled
----

新しい workerocs *Machine Set* の全てで `READY` と `AVAILABLE` のカラムに数値(この場合は `1` )が表示されるまで待ちます。このステップには10分ほどかかる場合があります。

[source,role="execute"]
----
watch "oc get machinesets -n openshift-machine-api"
----

.出力例:

----
NAME                                       DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-58kkd-nmncw-worker-us-east-2a      1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2b      1         1         1       1           21h
cluster-58kkd-nmncw-worker-us-east-2c      1         1         1       1           21h
cluster-58kkd-nmncw-workerocs-us-east-2a   1         1         1       1           3m55s
cluster-58kkd-nmncw-workerocs-us-east-2b   1         1         1       1           3m55s
cluster-58kkd-nmncw-workerocs-us-east-2c   1         1         1       1           3m55s
----
kbd:[Ctrl+C]を押すと終了できます。

ここで、新しい *Machine* がOCPクラスターに追加されていることを確認してみましょう。全ての *Machine* の `STATE` が `Running` であることを確認します。

[source,role="execute"]
----
oc get machines -n openshift-machine-api | egrep 'NAME|workerocs'
----

.出力例:

----
NAME                                             PHASE     TYPE         REGION      ZONE         AGE
cluster-58kkd-nmncw-workerocs-us-east-2a-sn8zd   Running   m5.4xlarge   us-east-2   us-east-2a   4m13s
cluster-58kkd-nmncw-workerocs-us-east-2b-f5bwx   Running   m5.4xlarge   us-east-2   us-east-2b   4m13s
cluster-58kkd-nmncw-workerocs-us-east-2c-9lctx   Running   m5.4xlarge   us-east-2   us-east-2c   4m13s
----

workerocs *Machine* が使用しているAWS EC2インスタンスタイプが `m5.4xlarge` であることがわかります。

NOTE: `m5.4xlarge` インスタンスタイプは、16 vCPUと64GB MEMのリソースを持ちます。このリソース量はODFで推奨されるスペックです。 +

最後に、3つのworker nodeが追加されて6つになっていることを確認します。全てのworker nodeの `STATUS` が `Ready` であることを確認します。

[source,role="execute"]
----
oc get nodes -l node-role.kubernetes.io/worker -l '!node-role.kubernetes.io/master'
----
.出力例:
----
NAME                                         STATUS   ROLES    AGE     VERSION
ip-10-0-128-156.us-east-2.compute.internal   Ready    worker   21h     v1.22.3+b93fd35
ip-10-0-157-232.us-east-2.compute.internal   Ready    worker   2m18s   v1.22.3+b93fd35
ip-10-0-171-65.us-east-2.compute.internal    Ready    worker   2m14s   v1.22.3+b93fd35
ip-10-0-181-21.us-east-2.compute.internal    Ready    worker   21h     v1.22.3+b93fd35
ip-10-0-206-84.us-east-2.compute.internal    Ready    worker   2m17s   v1.22.3+b93fd35
ip-10-0-214-18.us-east-2.compute.internal    Ready    worker   21h     v1.22.3+b93fd35
----

以上で、worker nodeの追加ができました。

NOTE: UPI(User Provisioned Infrastructure)方式でインストールしたOCPクラスターでは、Machine SetおよびMachineは利用できません。その場合は手作業でクラスターにnodeを追加して下さい。

== 2-1-2. 追加したworker nodeにODFで使用するためのラベルを付ける

ODFを稼働させるnodeには、`cluster.ocs.openshift.io/openshift-storage` という特定のラベルが付いている必要があります。 +
後段のLabで学習する、"ODF Operator"によって様々なODFを構成するPodがデプロイされますが、これらのPodはこのラベルが付いているnodeで稼働するようになっているためです。

新しいworker nodeに、`cluster.ocs.openshift.io/openshift-storage` のラベルを付けます。

[source,role="execute"]
----
oc label $(oc get node -l 'role=storage-node','topology.kubernetes.io/zone=us-east-2a' -o name) cluster.ocs.openshift.io/openshift-storage=""
oc label $(oc get node -l 'role=storage-node','topology.kubernetes.io/zone=us-east-2b' -o name) cluster.ocs.openshift.io/openshift-storage=""
oc label $(oc get node -l 'role=storage-node','topology.kubernetes.io/zone=us-east-2c' -o name) cluster.ocs.openshift.io/openshift-storage=""
----

ODF用のラベルが付いていることを確認してみましょう。

[source,role="execute"]
----
oc get nodes -l cluster.ocs.openshift.io/openshift-storage=
----
.出力例:
----
NAME                                         STATUS   ROLES    AGE     VERSION
ip-10-0-157-232.us-east-2.compute.internal   Ready    worker   4m10s   v1.22.3+b93fd35
ip-10-0-171-65.us-east-2.compute.internal    Ready    worker   4m6s    v1.22.3+b93fd35
ip-10-0-206-84.us-east-2.compute.internal    Ready    worker   4m9s    v1.22.3+b93fd35
----

---
以上で、「Lab 2-1: OpenShift Data Foundationをデプロイするためのnodeを準備する」は完了です。 +
次は link:ocs4-2[Lab 2-2: ODFクラスターを作成する] に進みます。

